version: '3.3'

services:

  postgres:
    image: postgres:10
    restart: on-failure
    environment:
      POSTGRES_USER: some_user
      POSTGRES_PASSWORD: some_pass
      POSTGRES_DB: unison_dev
    ports:
    - 5432:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.3
    restart: on-failure
    ports:
    - 8080:8080
    depends_on:
    - postgres

#  nodejs:
#    build:
#      context: ./
#      dockerfile: ./docker/Dockerfile
#    restart: on-failure
#    ports:
#    - 3000:3000
#    depends_on:
#    - postgres
#    volumes:
#    - ./:/usr/src/app
#    - /usr/src/app/node_modules
#    - /usr/src/app/logs
#    - nodejs-statics:/usr/src/app/statics
#    environment:
#      NODE_ENV: development
#      DATABASE_URL: postgres://some_user:some_pass@postgres:5432/unison_dev?ssl=true
#      PORT: 3000
#      SECRET: this-have-to-be-changed
#    command: [ "npm", "run", "dev" ]
#    # command: [ "sleep", "3600" ]

volumes:
  postgres-data:
