FROM node:8.11.3

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/package.json
RUN yarn

# Bundle app source
COPY . /usr/src/app

CMD [ "npm", "start" ]
